source 'https://rubygems.org'
gem 'rails', '4.0.0.beta1'
gem 'mysql2', '0.3.12b5'
gem 'puma'
gem 'capistrano'
gem 'rvm-capistrano'
gem 'thinking-sphinx'
gem 'bcrypt-ruby'
gem 'nokogiri'
gem 'paperclip'
gem 'twitter'
gem 'geocoder'
gem 'therubyracer'
group :assets do
	 gem 'sass-rails',   '~> 4.0.0.beta1'
	 gem 'coffee-rails', '~> 4.0.0.beta1'
	 gem 'uglifier', '>= 1.0.3'
end
gem 'haml-rails'
gem 'jquery-rails'
# gem 'turbolinks'
gem 'jbuilder', '~> 1.0.1'
