development:
  adapter: mysql2
  database: renegade_development
  username: root
  password: 
  host: localhost
  port: 3306

production:
  adapter: mysql2
  database: renegade_production
  username: noah
  password: production
  host: 127.0.0.1
  port: 3306